### ISSUE TITLE
Error in the Modbus code

### ISSUE THREAD

**Issue by ghost** [OStephan29/decodeZCL#5]
Hello,

I work for a French company that uses your devices and I am in charge of developing an application based on your code to interpret the information received. 

I spotted an error in your code when I receive frames from your Modbus product. Indeed, the last byte of the payload is not interpreted by the program. The problem is at line 163 where the loop does not run until the last byte but ends just before.
There are 2 ways to correct the problem : 
- for( var j = 0; j <= decoded.data.size -1; j++ )
- for( var j = 0; j < decoded.data.size; j++ )

I am available for more information.

**Comment by Watteco** [comment]
corrected on commit ad718dea56dae64cc9b968c87bbcc7199564d7e

**Comment by Watteco** [comment]
corrected on commit ad718dea56dae64cc9b968c87bbcc7199564d7e
